apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bad-indents
  name: bad-indents
spec:
containers:
     - image: busybox
       name: bad-indents
         res ources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
