apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
spec:
  containers:
  - args:
    - sh
    - -c
      sleep 1d
    image: ubuntu
    name:   ubuntu-sleeper
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
